def get_obj_type_from_ID(ID):
    if ID<3e7:
        return 'SNIa'
    elif ID<4e7:
        return 'SNII'
    elif ID<5e7:
        return 'SNIb'
    elif ID<6e7:
        return 'SNIc'
    elif ID<7e7:
        return 'SNIax'
    elif ID<8e7:
        return 'PISN-He'
    elif ID<9e7:
        return 'PISN-Hy'
    elif ID<10**7.1:
        return 'KN'
    elif ID<10**9.3:
        return 'star'
    else:
        return 'galaxy'